spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_generator?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: eorud4869!
    driver-class-name: com.mysql.cjdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# OpenAI API 설정 (환경변수로 관리)
# openai:
#   api:
#     key: ${OPENAI_API_KEY}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.hackthon.blog_generator_backend: DEBUG
    org.springframework.web: DEBUG

server:
  port: 8081
